import { Unit, Tutor, Conversation, Transaction } from "./types";

export const units: { code: Unit; name: string }[] = [
  { code: "INFO2222", name: "Computing 2" },
  { code: "INFO1110", name: "Introduction to Programming" },
  { code: "COMP2017", name: "Systems Programming" },
  { code: "SOFT3202", name: "Software Construction and Design 2" },
  { code: "ELEC1601", name: "Foundations of Computer Systems" },
  { code: "DATA2001", name: "Data Science" },
  { code: "ECON1001", name: "Introductory Microeconomics" },
];

export const topicOptions = [
  "programming",
  "web security",
  "databases",
  "algorithms",
  "statistics",
  "exam preparation",
  "assignment feedback",
];

export const initialTutors: Tutor[] = [
  {
    id: 1,
    name: "Alex Chen",
    initials: "AC",
    degree: "Software Engineering",
    year: "3rd Year",
    units: ["INFO2222", "COMP2017"],
    rating: 4.9,
    reviewsCount: 38,
    rate: 42,
    next: "Today, 6:30 pm",
    topics: ["programming", "web security", "databases", "assignment feedback"],
    focus: "SQL, React, security concepts, assignment feedback",
    sessions: 112,
    response: "Under 1 hour",
    repeat: 78,
    headline: "Making INFO2222 concepts practical and clear.",
    about:
      "I break complex system and security concepts into visual, testable examples. Sessions are collaborative and focused on helping you build independent problem-solving skills.",
    promoted: true,
    availability: ["Today · 6:30 pm", "Thu · 4:00 pm", "Sat · 10:00 am"],
    reviews: [
      {
        id: 1,
        author: "Jamie L.",
        rating: 5,
        unit: "INFO2222",
        text: "Alex made SQL injection and access control click for me. Clear, patient, and practical.",
        date: "2 weeks ago",
      },
      {
        id: 2,
        author: "Morgan K.",
        rating: 5,
        unit: "COMP2017",
        text: "Great debugging approach without giving away answers.",
        date: "1 month ago",
      },
    ],
  },
  {
    id: 2,
    name: "Priya Nair",
    initials: "PN",
    degree: "Data Science",
    year: "4th Year",
    units: ["DATA2001", "INFO1110"],
    rating: 5.0,
    reviewsCount: 27,
    rate: 38,
    next: "Tomorrow, 11:00 am",
    topics: ["statistics", "programming", "exam preparation"],
    focus: "Python, statistics, data wrangling, exam preparation",
    sessions: 84,
    response: "About 2 hours",
    repeat: 82,
    headline: "Structured support for data and programming.",
    about:
      "I love helping students move from uncertainty to a clear study plan using structured explanations and worked examples.",
    availability: ["Tue · 11:00 am", "Wed · 5:30 pm", "Sun · 2:00 pm"],
    reviews: [
      {
        id: 1,
        author: "Casey R.",
        rating: 5,
        unit: "DATA2001",
        text: "Explanations and practical practice worksheet.",
        date: "1 week ago",
      },
    ],
  },
  {
    id: 3,
    name: "Minh Tran",
    initials: "MT",
    degree: "Computer Science",
    year: "4th Year",
    units: ["SOFT3202", "INFO2222"],
    rating: 4.8,
    reviewsCount: 19,
    rate: 40,
    next: "Wednesday, 5:00 pm",
    topics: ["programming", "web security", "algorithms"],
    focus: "Design patterns, testing, React, code review",
    sessions: 61,
    response: "Under 3 hours",
    repeat: 71,
    headline: "Build stronger software thinking, one pattern at a time.",
    about:
      "My sessions emphasize reasoning, testing, and maintainable design. We review your approach while keeping submitted work strictly your own.",
    availability: ["Wed · 5:00 pm", "Fri · 3:00 pm", "Sat · 1:00 pm"],
    reviews: [
      {
        id: 1,
        author: "Taylor S.",
        rating: 5,
        unit: "SOFT3202",
        text: "Useful code review and testing guidance.",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: 4,
    name: "Sophie Williams",
    initials: "SW",
    degree: "Economics",
    year: "Honours",
    units: ["ECON1001"],
    rating: 4.9,
    reviewsCount: 45,
    rate: 35,
    next: "Today, 7:00 pm",
    topics: ["exam preparation", "statistics", "assignment feedback"],
    focus: "Microeconomics, diagrams, exam technique",
    sessions: 138,
    response: "Under 1 hour",
    repeat: 86,
    headline: "Economics explained with intuition before equations.",
    about:
      "I help students understand the concepts behind economic models, then apply them systematically to practice problems.",
    availability: ["Today · 7:00 pm", "Thu · 6:00 pm", "Sun · 4:00 pm"],
    reviews: [
      {
        id: 1,
        author: "Ari P.",
        rating: 5,
        unit: "ECON1001",
        text: "Clear diagrams and practical exam technique.",
        date: "5 days ago",
      },
    ],
  },
  {
    id: 5,
    name: "Daniel Kim",
    initials: "DK",
    degree: "Mechatronic Engineering",
    year: "4th Year",
    units: ["ELEC1601", "COMP2017"],
    rating: 4.7,
    reviewsCount: 21,
    rate: 45,
    next: "Friday, 3:30 pm",
    topics: ["programming", "algorithms", "exam preparation"],
    focus: "C, memory, digital systems, debugging",
    sessions: 73,
    response: "About 3 hours",
    repeat: 69,
    headline: "Understand system internals, not just syntax.",
    about:
      "We trace programs, inspect memory, and build repeatable debugging habits through guided practice.",
    availability: ["Fri · 3:30 pm", "Sat · 9:00 am", "Sun · 11:00 am"],
    reviews: [
      {
        id: 1,
        author: "Noah J.",
        rating: 5,
        unit: "COMP2017",
        text: "The memory layout explanations resolved key blockers.",
        date: "2 months ago",
      },
    ],
  },
  {
    id: 6,
    name: "Olivia Brown",
    initials: "OB",
    degree: "Advanced Computing",
    year: "3rd Year",
    units: ["INFO1110", "DATA2001"],
    rating: 4.9,
    reviewsCount: 31,
    rate: 36,
    next: "Thursday, 1:00 pm",
    topics: ["programming", "statistics", "assignment feedback"],
    focus: "Python fundamentals, pandas, study planning",
    sessions: 96,
    response: "Under 2 hours",
    repeat: 80,
    headline: "Structured support for coding foundations.",
    about:
      "A calm space to practice programming fundamentals and learn how to diagnose errors independently.",
    availability: ["Thu · 1:00 pm", "Fri · 5:00 pm", "Sun · 10:30 am"],
    reviews: [
      {
        id: 1,
        author: "Sam D.",
        rating: 5,
        unit: "INFO1110",
        text: "Patient and encouraging foundations support.",
        date: "1 week ago",
      },
    ],
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 1,
    tutorId: 1,
    preview: "See you Thursday. Bring your SQL query draft.",
    unit: "INFO2222",
    session: "Thu 17 Sep · 4:00 pm",
    unread: true,
    messages: [
      {
        id: 1,
        sender: "them",
        text: "Hi Jamie. I reviewed your learning goals. We can focus on SQL joins and input validation.",
        time: "10:24 am",
      },
      {
        id: 2,
        sender: "me",
        text: "Perfect. I have a query draft that keeps returning duplicate rows.",
        time: "10:27 am",
      },
      {
        id: 3,
        sender: "them",
        text: "See you Thursday. Bring your SQL query draft.",
        time: "10:29 am",
      },
    ],
  },
  {
    id: 2,
    tutorId: 2,
    preview: "I have shared the practice worksheet.",
    unit: "DATA2001",
    session: "Sun 20 Sep · 2:00 pm",
    unread: true,
    messages: [
      {
        id: 1,
        sender: "them",
        text: "I have shared the practice worksheet. Try questions 1 to 4 before Sunday.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 3,
    tutorId: 3,
    preview: "Your session is confirmed.",
    unit: "SOFT3202",
    session: "Wed 23 Sep · 5:00 pm",
    unread: false,
    messages: [
      {
        id: 1,
        sender: "them",
        text: "Your session is confirmed. We will look at testing strategy and dependency injection.",
        time: "Monday",
      },
    ],
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: "TFT-1048",
    student: "Jamie N.",
    unit: "INFO2222",
    date: "18 Sep 2026",
    duration: 60,
    gross: 42,
    fee: 4.2,
    status: "Paid",
  },
  {
    id: "TFT-1041",
    student: "Morgan K.",
    unit: "COMP2017",
    date: "15 Sep 2026",
    duration: 60,
    gross: 42,
    fee: 4.2,
    status: "Paid",
  },
  {
    id: "TFT-1032",
    student: "Taylor S.",
    unit: "INFO2222",
    date: "11 Sep 2026",
    duration: 45,
    gross: 31.5,
    fee: 3.15,
    status: "Paid",
  },
  {
    id: "TFT-1027",
    student: "Casey R.",
    unit: "COMP2017",
    date: "8 Sep 2026",
    duration: 60,
    gross: 42,
    fee: 4.2,
    status: "Processing",
  },
];
